---
# tasks file for ovirtguestagent

- name: "[NET INSTALL] oVirt Guest Agent para {{ ansible_distribution }}/{{ ansible_distribution_major_version }}"
  when: ansible_distribution == "CentOS"
  yum:
    name: [ 'http://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm','epel-release' ] 
    state: latest
    disable_gpg_check: yes
  register: result

- yum:
    name: ovirt-guest-agent-common
    state: latest
  when: result is success
  notify:
    - Enable ovirt-guest-agent
    - Restart ovirt-guest-agent

## END PLAYBOOK
...